"""
Analyze the random seeds generated by GATE

Author: Martin Rädler
"""
# Python libraries
import sys
from os.path import dirname
from glob import glob
import numpy as np
import matplotlib.pyplot as plt


def main():
    analyze_digits = False
    analyze_values = False

    # home_dir = '/data/5/users/raedler'
    # geom_path = home_dir + '/J-PET/Gate_Output/Sensitivity_maps/SiPM_6mm_depth_3cm_cylinders'
    # sim_paths = glob(geom_path + '/*')
    # random_seeds = load_random_seeds_two_columns(sim_paths)

    home_dir = dirname(dirname(sys.path[0]))
    geom_path = home_dir + '/J-PET/Gate_Output/Sensitivity_maps/TB_6_30_3_BI_4_18_3_Box'
    sim_paths = glob(geom_path + '/*')
    random_seeds = load_random_seeds_one_column(sim_paths)

    if analyze_digits:
        digits_str = ''.join(random_seeds.astype(str))
        digits = np.array([int(digit) for digit in digits_str])

        digits_rand = np.random.choice(10, digits.size)

        h = np.bincount(digits)
        h_rand = np.bincount(digits_rand)

        fig, ax = plt.subplots()
        ax.bar(np.arange(h.size), h, alpha=0.5, label='GATE seeds')
        ax.bar(np.arange(h_rand.size), h_rand, alpha=0.5, label='np.random')
        ax.set_xticks(np.arange(10))
        ax.legend()
        plt.show()

    if analyze_values:
        bin_edges = np.linspace(0, np.max(random_seeds), 50)
        bin_centers = (bin_edges[1:] + bin_edges[:-1]) / 2
        bin_widths = bin_edges[1:] - bin_edges[:-1]
        h, _ = np.histogram(random_seeds, bins=bin_edges)

        fig, ax = plt.subplots()
        ax.bar(bin_centers, h, width=bin_widths)
        plt.show()

    n_seeds = random_seeds.size
    n_unique_seeds = np.unique(random_seeds).size

    print('Among %d seeds, there are %d identical seeds.' % (n_seeds, n_seeds - n_unique_seeds))

    return 0


def load_random_seeds_two_columns(sim_paths):
    random_seeds = []

    for ii in range(len(sim_paths)):
        txt_content = np.loadtxt(sim_paths[ii] + '/random_seeds.txt', dtype=np.int64, delimiter=' ')
        random_seeds.append(txt_content[:, 1])

    return np.concatenate(random_seeds)


def load_random_seeds_one_column(sim_paths):
    random_seeds = []

    for ii in range(len(sim_paths)):
        txt_content = np.loadtxt(sim_paths[ii] + '/random_seeds.txt', dtype=np.int64)
        random_seeds.append(txt_content)

    return np.concatenate(random_seeds)


if __name__ == "__main__":
    main()
